#!/bin/bash


HADOOP_VERSION=3.3.3
METASTORE_VERSION=3.0.0
HIVE_VERSION=3.1.3
HIVE_STANDALONE_METASTORE=https://downloads.apache.org/hive/hive-standalone-metastore-${METASTORE_VERSION}/hive-standalone-metastore-${METASTORE_VERSION}-bin.tar.gz
HADOOP=https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz
echo ${HIVE_STANDALONE_METASTORE}
echo ${HADOOP}